<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('posts', function (Blueprint $table) {
            // "Key Takeaways" bullets (array of strings) + FAQ pairs (array of
            // {question, answer}). Generated by the AI rewrite; power the on-page
            // summary box, the FAQ block, and FAQPage JSON-LD.
            $table->json('takeaways')->nullable()->after('body');
            $table->json('faqs')->nullable()->after('takeaways');
        });
    }

    public function down(): void
    {
        Schema::table('posts', function (Blueprint $table) {
            $table->dropColumn(['takeaways', 'faqs']);
        });
    }
};
